### ISSUE TITLE
Issue with unicode characters

### ISSUE THREAD

**Issue by jcubic** [jcubic/leash#10]
There is issue in unicode characters as output of shell command the same as input form user.

for instance `echo ą` or ls in directory that content file zając.

**Comment by sskras** [comment]
So was the issue fixed then?

**Comment by jcubic** [comment]
I think so, do you have a problem? I don't use this project anymore, since I have real SSH on my new shared hosting now.

**Comment by sskras** [comment]
Not really. Just found the project and wondered what could be the single open issue about. :)

**Comment by sskras** [comment]
Thanks for the update.

**Comment by jcubic** [comment]
It seems that the commit with the fix is on devel branch. It was added when I still released new versions after few bug fixes and features. Will check if the solution works and release next version.

**Comment by sskras** [comment]
That's good to hear.
