### ISSUE TITLE
How i can use jargon ?

### ISSUE THREAD

**Issue by ZerooCool** [jcubic/leash#11]
I download the zip leash-master

Lancer le terminal et choisir un mot de passe root. ( TestAdmin )
Choisir un serveur ( localhost ) ?
Choisir un nom d'utilisateur ( Admin )
Choisir le répertoire home ( leash-master )
Autoriser les invités ( N )
Autoriser sudo pour les comptes utilisateurs ( N )
Mot de passe : TestAdmin

Login -> ( Admin / TestAdmin )
-->
jargon hacker
:'(
could not find driver

What can i do for use jargon ?

**Comment by jcubic** [comment]
You need to have installed: sqlite and Php sqlite libraries on your system. If you don't know how to install use Google with "how to install Php sqlite" with your OS you can also search in French. Leash use PDO extension for database it should be installed with sqlite Php module.
