### ISSUE TITLE
/bin/bash: .bashrc: No such file or directory

### ISSUE THREAD

**Issue by tommyjcode** [jcubic/leash#12]
When I run most commands, or even "test", I get "/bin/bash: .bashrc: No such file or directory".

I'm probably being stupid, but I would like some help. Thanks!

**Comment by jcubic** [comment]
Did you upload all the files to the server? .bashrc that is in repo if you use some linux/macos commands it will be ignored because it's hidden. Check if it's in root directory on the server.

**Comment by tommyjcode** [comment]
Thanks! I got it to work by creating my own .bashrc file! Thanks for the help, I will keep this in mind.

**Comment by jcubic** [comment]
If you want colors in some of the commnads like `ls` or `grep` you should use bashrc that is in repo, you can add more stuff but those are needed to for colors and for `man` command to give white/bold highlighting.
