### ISSUE TITLE
MIT license

### ISSUE THREAD

**Issue by jportoles** [jcubic/leash#3]
Hey, great work with Leash, it's looking like a pretty promising project. Would you consider moving it and its components like jsvi to MIT? We'd like to integrate leash in our workflow, and possibly contribute back if we make changes since it's written in our stack, but GPL is very restrictitive and we have some incompatibilities with it. If you could consider the switch it would save of us a lot of pain, since otherwise Leash fits the bill for us. Thanks!

**Comment by jcubic** [comment]
I can move to MIT but jsvi need to stay with GPL because I'm not original author of the plugin.

**Comment by jcubic** [comment]
but I don't know if I use jsvi if I don't need to use GPL for the whole thing.

**Comment by jportoles** [comment]
Ah, you are right, I saw the repo in your account so I didn't realize you didn't write jsvi. So, one option could be to keep two branches, one GPL version with jsvi, and another MIT without jsvi. That would make Leash "dual-licensed", where the user of Leash can pick the license branch that fits for them, which is a perfectly valid model. Would something like this work? 

Later on we could always integrate another javascript Vi(m) clone in this branch like [js-vim](https://github.com/itsjoesullivan/js-vim), which is MIT licensed and [web embbedable](https://github.com/itsjoesullivan/js-vim-embed/).

**Comment by jcubic** [comment]
version 0.10.0 have MIT license I needed to change license from GPL to MIT for two my other projects json-rpc and sysend.js. and needed to remove html2text now display of html on terminal don't work, I found MIT version but it don't work as the previous one.

**Comment by jcubic** [comment]
jsvi app have it's own repo https://github.com/jcubic/jsvi-app

**Comment by jportoles** [comment]
Great, that should work, no html on the terminal shouldn't be a big problem. Thanks!

**Comment by jcubic** [comment]
I've added a code (in devel branch) that will fetch jsvi and html2text from github on install.
