### ISSUE TITLE
Ajax error, pic

### ISSUE THREAD

**Issue by zank-it** [jcubic/leash#5]
![ajax](https://cloud.githubusercontent.com/assets/17980844/22932406/1654600a-f2c8-11e6-928e-3babe91dbcd0.PNG)

apache2 on ubuntu 16.04

SSL by let's encrypt (only secure)

Thanks

**Comment by jcubic** [comment]
did you check this? http://stackoverflow.com/questions/8266396/mb-convert-encoding-undefined-function-while-mbstring-is-enabled

I should probably add requirements to README.

**Comment by jcubic** [comment]
You need to install mbstring,

for php7.0 you can execute this:
```
sudo apt-get install php7.0-mbstring
sudo service php7.0-fpm restart
```
if you can't install anything I can make leash work when that function is unavailable.

**Comment by zank-it** [comment]
Thanks
it works

**Comment by zank-it** [comment]
```
apt-get install php7.0-mbstring
service apache2 restart
```

**Comment by zank-it** [comment]
And also

```
apt-get install php7.0-zip
apt-get install php5-curl
/etc/init.d/apache2 restart
```
