### ISSUE TITLE
Cannot use object of type stdClass as array in leash/lib/Service.php line 449

### ISSUE THREAD

**Issue by alexanderdevm** [jcubic/leash#6]
`
 public function configure($settings) {
        if ($this->installed()) {
            throw new Exception("You can't call this function, leash already installed");
        }
line 449:        if ($settings['username'] == 'guest' || $settings['username'] == 'root') {
            throw new Exception("You can't use " . $settings['username'] . " as userna".
                                "me because it's special account");
        }
`

It does not like $settings['username']

**Comment by jcubic** [comment]
Thanks for the report, it should be `$settings->username` it's in master but it will be in next version (I should commit to devel branch) try 0.14.0 release https://github.com/jcubic/leash/releases/tag/0.14.0

**Comment by alexanderdevm** [comment]
I did play around with by changing the whole function to use object reference instead, the errors disappeared although the setup would hang. Once i will have a chance, i will test on the latest build.

**Comment by jcubic** [comment]
Fixed both issues, tested installation and it works, I've also updated readme with requirements.

**Comment by alexanderdevm** [comment]
Thank you for the update, will definitely check it out.
