### ISSUE TITLE
JSONRPCError code":100

### ISSUE THREAD

**Issue by Mark-Joy** [jcubic/leash#7]
Hello,
I uploaded all file into server, but  when open index.php in my browser I got this error. Could you help me out?

`{"jsonrpc":"2.0","result":null,"id":null,"error":{"code":100,"message":"Server error","error":{"name":"PHPErorr","code":2,"message":"unlink(\/home\/content\/a2pewpnaspod04_data03\/66\/41247166\/html\/usr\/php\/leash\/config.json): No such file or directory","file":"\/home\/content\/a2pewpnaspod04_data03\/66\/41247166\/html\/usr\/php\/leash\/lib\/Service.php","at":249,"line":"        unlink($filename);"},"name":"JSONRPCError"}}`

**Comment by Mark-Joy** [comment]
I comment out line 249 of Service.php and now it is running.
`//unlink($filename);`

**Comment by jcubic** [comment]
Hi, I've added that line because I didn't get truncated file on fopen as docs say and got json from prevoius save after last json. Can you check if `@unlink($filename);` work for you?

**Comment by jcubic** [comment]
Or I can just check if file exists.

**Comment by jcubic** [comment]
Added the check.

**Comment by Mark-Joy** [comment]
Thank you! I updated to latest version through "update" command. It works perfectly now!!
