### ISSUE TITLE
Where to install shell-exec or exec?

### ISSUE THREAD

**Issue by PLKids** [jcubic/leash#8]
Where should I install exec or shell-exec on Mac using MAMP? I've tried many locations, none of which have worked.

EDIT: I'm asking because without this, apparently no commands work.

**Comment by jcubic** [comment]
1. After installation did you get message that one of the exec functions was found?

2. Do you have in php.ini one of the exec function on the list of `disable_functions`?

**Comment by PLKids** [comment]
No for both, but maybe because I am new to this and need to understand where to install on my computer exec.

**Comment by jcubic** [comment]
I've found the error, on a mac `echo -n x` return `-n x` not `x`. fixed in version 0.17.0.

You can put the files anywhere when server can access them I've put all files in `/Applications/MAMP/htdocs/leash`

**Comment by PLKids** [comment]
Thank you! Works great.
