### ISSUE TITLE
host does not allow curl 

### ISSUE THREAD

**Issue by Mark-Joy** [jcubic/leash#9]
Hello, 
During installation, I got the below error. I think my host does not allow curl.
Is it checking github to get version updated?
Is there any way to by pass this check?
```
Detect Shell
Test Shell 'exec' [PASS]
Using shell exec
curl error Failed to connect to github.com port 443: Connection refused
```

Thank you!

**Comment by jcubic** [comment]
can you create test.php file like this:
```
<?php
    $ch = curl_init("http://google.com");    // initialize curl handle
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
    $data = curl_exec($ch);
    print($data);
?>
```
and tell me the output is. Maybe you have a firewall that restrict the curl as in this [SO answer](https://stackoverflow.com/a/9923212/387194)

**Comment by Mark-Joy** [comment]
in host that allows curl I got google page.
in host that does not allow curl I got blank page.

I can install leash fine on host that allows curl, but how to install on the other one?

**Comment by jcubic** [comment]
right now you can't it seems, will fix it as soon as I find some free time, the curl is used to fetch the jsvi editor because it have different license and on each request to check if there are no updates.

I can disable curl and maybe write code that will use perl instead (for curl).

**Comment by jcubic** [comment]
In devel branch it should now work wihout curl. it show warning that curl is disabled that can be discarded by updating show_messages option in config.json.

**Comment by jcubic** [comment]
In version 0.18.0. I didn't added curl using cgi because to use curl in perl you need to install WWW:Curl and I don't know if python will always be installed.

**Comment by Mark-Joy** [comment]
Hello,
Thank you very much for new release!!
It seems that curl extension is available in php, but they block the port or something. I don't really know.
I change the below code in service.php and now can run leash on host which doesn't allow curl.

```
function is_curl_enabled()  {
    //return function_exists('curl_version');
	return false;
}
```
